import os
import glob
import logging
from pathlib import Path

configfile: "config/config.yaml"

trials = config["trials"]
savepath = config["savepath"]
name = config["name"]
clean_up = config["clean_up"]
make_figs = config["make_figs"]
fig_ext = config["fig_ext"]

merged_trials = f"{savepath}/{name}_trials_merged_{trials}.csv"

existing_trials = 0
existing_merged_file = ""

### Final outputs

if make_figs:
    spearman_plot = (
        f"{savepath}/{name}_spearman.pdf" #{fig_ext}"
    )
    all_figs = spearman_plot
else:
    all_figs = []

stats_file = (
    f"{savepath}/{name}_stats.json"
)

def prepare():
    existing_merged_file = Path(f"{savepath}/{name}_trials_merged_*.csv")
    matched_files = glob.glob(str(existing_merged_file))
    if matched_files:
        results_file = matched_files[0]
        existing_trials = int(results_file.split("_trials_merged_")[1].split(".")[0])
        trials_to_run = trials - existing_trials

        if trials_to_run < 1:
            print(f"{existing_trials} trials already exist; {trials} requested")
        else:
            print(f"Found: {existing_trials} existring trials, appending {trials_to_run} new ones...")

        return existing_trials
    return 0

existing_trials = prepare()

rule all:
    input:
        all_figs,
        stats_file

rule run_trial:
    output:
        f"{savepath}/{name}_trial_{{i}}.csv"
    params:
        script="workflow/scripts/main.py"
    conda:
        "envs/environment.yaml"
    shell:
        "python {params.script} {savepath} {name} {wildcards.i}"

rule merge_trials:
    input:
        expand(f"{savepath}/{name}_trial_{{i}}.csv", i=range(existing_trials+1, trials + 1))
    output:
        merged_trials
    params:
        script="workflow/scripts/merge_trials.py"
    conda:
        "envs/environment.yaml"
    shell:
        """
        echo {existing_trials} wtf
        python {params.script} {savepath} {name} {trials} {clean_up}
        """

rule compute_results:
    input:
        merged_trials
    output:
        all_figs,
        stats_file
    params:
        script="workflow/scripts/compute_results.py"
    conda:
        "envs/environment.yaml"
    shell:
        """
        python {params.script} {savepath} {name} {trials} {make_figs}
        """