name: pre-commit

on: workflow_dispatch
  # pull_request:
  # push:
  #   branches: [ main, master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - uses: pre-commit/action@v2.0.0
